
//staff
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'
export const FETCH_STAFF_FAIL = 'FETCH_STAFF_FAIL'
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS'
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS'
export const DELETE_STAFF_LOADING = ' DELETE_STAFF_LOADING'
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';

//department
export const ADD_DEPARTMENT = 'ADD_DEPARTMENTS'
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENT_FAIL = 'DEPARTMENT_SUCCESS';

//salary
export const STAFFSALARY_LOADING = 'STAFFSALARY_LOADING';
export const STAFFSALARY_SUCCESS = 'STAFFSALARY_SUCCESS'
export const STAFFSALARY_FAIL = 'STAFFSALARY_FAIL'

