export const ADD_STAFF_LOADING = ' ADD_STAFF_LOADING';
export const ADD_STAFF_SUCCESS = ' ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL'

export const DELETE_STAFF_LOADING = ' DELETE_STAFF_LOADING';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';

export const STAFFS_LOADING = 'STAFFS_LOADING';
export const FETCH_STAFFS_FAIL = ' FETCH_STAFFS_FAILS';
export const FETCH_STAFFS_SUCCESS = 'FETCH_STAFFS_SUCCESS';

export const DEPARTMENT_LOADING = ' DEPARTMENT_LOADING';
export const DEPARTMENT_SUCCESS = ' DEPARTMENT_SUCCESS';

export const STAFFSALARY_LOADING = 'STAFFSALARY_LOADING';
export const STAFFSALARY_SUCCESS = 'STAFFSALARY_SUCCESS'
export const STAFFSALARY_FAIL = 'STAFFSALARY_FAIL'

export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL'